apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: "{{ .Release.Name }}-api-gateway-bc"
  namespace: default
spec:
  timeoutSec: 120
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    type: HTTP
    requestPath: /api/playground/assistant/health
    port: 80
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
