apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: playground-sa@playground-production-441511.iam.gserviceaccount.com
  name: {{ .Values.serviceAccount }}
  namespace: default